In [1]:
import numpy as np

In [5]:
x=np.random.randint(1,10,(10,5))

In [6]:
x

array([[2, 9, 6, 7, 1],
       [8, 3, 5, 8, 5],
       [7, 4, 2, 3, 7],
       [9, 6, 4, 7, 2],
       [2, 8, 1, 1, 5],
       [3, 8, 2, 6, 8],
       [6, 2, 7, 9, 9],
       [3, 5, 9, 9, 7],
       [6, 4, 5, 6, 4],
       [6, 5, 1, 9, 6]])

In [9]:
y=x[0]-x

In [12]:
d=y*y

In [20]:
np.sqrt(d.sum(axis=1)[1:]).argmin()

7

In [21]:
x=np.random.randint(0,10,(10,5))

In [23]:
r1=x[2]
r2=x[5]

In [33]:
d1=np.sqrt(((r1-x)*(r1-x)).sum(axis=1))
d2=np.sqrt(((r2-x)*(r2-x)).sum(axis=1))

In [37]:
d1<d2

array([False,  True,  True, False, False, False,  True, False,  True,
       False])

In [36]:
d2

array([ 5.29150262,  8.18535277,  7.        ,  4.35889894,  7.41619849,
        0.        , 12.08304597,  8.88819442,  6.8556546 , 13.        ])

In [ ]:
### Numpy Set 2

In [44]:
x=np.random.randint(0,10,(10,5))

In [48]:
len(x)

10

In [51]:
x[:,0]

array([2, 5, 1, 1, 6, 3, 1, 3, 9, 3])

In [53]:
### Basic Mathematics( Descriptive Statistics)

In [54]:
x=np.array([1,2,3,4])

In [55]:
x.mean()

2.5

In [56]:
x=np.random.randint(0,100,10)

In [57]:
x

array([39, 69, 14, 18, 41, 74, 93,  8, 38, 42])

In [61]:
first_qrt=np.quantile(x,0.25)

In [65]:
third_qrt=np.quantile(x,0.75)

In [63]:
first_qrt

23.0

In [66]:
third_qrt


62.25

In [68]:
UTV =third_qrt+1.5*(third_qrt-first_qrt)

In [69]:
UTV

121.125

In [74]:
x=np.random.randint(0,1000,(10,3))

In [78]:
c1=x[:,0]
c2=x[:,1]
c3=x[:,2]

In [81]:
q1_c1=np.quantile(c1,0.25)
q3_c1=np.quantile(c1,0.75)
iqr_c1=q3_c1-q1_c1
utv_c1=q3_c1+1.5*(iqr_c1)
ltv_c1=q1_c1-1.5*(iqr_c1)
print(q1_c1,q3_c1,iqr_c1,utv_c1,ltv_c1)

392.5 841.25 448.75 1514.375 -280.625


In [83]:
c1>utv_c1

array([False, False, False, False, False, False, False, False, False,
       False])

In [85]:
c1<ltv_c1

array([False, False, False, False, False, False, False, False, False,
       False])

In [86]:
q1_c2=np.quantile(c2,0.25)
q3_c2=np.quantile(c2,0.75)
iqr_c2=q3_c2-q1_c2
utv_c2=q3_c2+1.5*(iqr_c2)
ltv_c2=q3_c2-1.5*(iqr_c2)
print(q1_c2,q3_c2,iqr_c2,utv_c2,ltv_c2)

380.5 732.75 352.25 1261.125 204.375


In [87]:
x

array([[403, 146, 758],
       [389, 757, 820],
       [742, 372, 679],
       [812, 642, 286],
       [851, 660,  69],
       [271, 822, 596],
       [ 50, 659, 792],
       [854, 406, 866],
       [877, 204, 606],
       [491, 873, 445]])

In [88]:
x=np.random.randint(0,10,100)

In [90]:
x.std()

2.877915912600644

In [91]:
x.var()

8.282399999999999

In [92]:
x=np.random.randint(0,10,(5,2))

In [100]:
c1=x[:,0]
c2=x[:,1]

In [98]:
np.corrcoef(x[:,0],x[:,1])

array([[1.        , 0.06072327],
       [0.06072327, 1.        ]])

In [ ]:
   c1  c2
c1 
c2      

In [101]:
#### Numpy Correlation

In [102]:
x=np.random.randint(0,10,(10,2))

In [106]:
c1=x[:,0]
c2=x[:,1]

In [114]:
top=((c1-c1.mean())*(c2-c2.mean())).sum()

In [115]:
bot=np.sqrt((((c1-c1.mean())**2).sum())*(((c2-c2.mean())**2).sum()))

In [116]:
top/bot

-0.32660340382163194

In [117]:
np.corrcoef(c1,c2)

array([[ 1.       , -0.3266034],
       [-0.3266034,  1.       ]])