NUMPY

In [1]:
a=[1,2,3]

In [2]:
import numpy as np
a=np.array(a)

In [3]:
type(a)

numpy.ndarray

In [4]:
a/2

array([0.5, 1. , 1.5])

In [5]:
a

array([1, 2, 3])

Functions

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#Interview question

In [11]:
a=[1,2,3,4]
b=[1,'analytics','data']

In [12]:
x=np.array(a)
y=np.array(b)

In [13]:
print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
type(a[0]),type(a[1]),type(a[2]),type(a[3])

(int, int, int, int)

In [15]:
type(x[0]),type(x[1]),type(x[2]),type(x[3])

(numpy.int32, numpy.int32, numpy.int32, numpy.int32)

In [17]:
type(b[0]),type(b[1]),type(b[2])

(int, str, str)

In [19]:
type(y[0]),type(y[1]),type(y[2]) 

(numpy.str_, numpy.str_, numpy.str_)

Set 2 : Random Functions

In [20]:
np.random.randint(0,10)

9

In [22]:
np.random.randint(0,10,3)

array([7, 5, 1])

In [23]:
np.random.randint(1,9,(2,3))

array([[8, 6, 4],
       [1, 8, 5]])

In [24]:
np.random.randn(7)

array([-0.83065203, -1.22137679,  0.46751577, -0.01296096,  0.26224683,
        0.49787604, -0.9005339 ])

Set 2b

In [30]:
x=np.random.randint(0,10,5)
x

array([1, 1, 9, 3, 1])

In [31]:
x.min()

1

In [33]:
x.max()

9

In [34]:
x.argmax() #index of the max value

2

In [36]:
x.argmin()

0

lift

In [37]:
f=np.random.randint(10,20,100)
f

array([10, 19, 13, 11, 18, 11, 14, 13, 17, 18, 18, 15, 12, 16, 18, 18, 14,
       10, 18, 13, 18, 16, 10, 14, 11, 18, 19, 17, 19, 16, 15, 19, 19, 17,
       10, 16, 14, 16, 19, 13, 11, 11, 13, 15, 17, 17, 15, 19, 15, 16, 11,
       16, 19, 14, 15, 13, 10, 14, 11, 18, 14, 12, 17, 13, 11, 10, 10, 17,
       13, 17, 17, 17, 19, 15, 10, 10, 13, 19, 19, 10, 19, 12, 16, 14, 11,
       13, 14, 16, 12, 11, 11, 18, 17, 18, 19, 17, 17, 16, 13, 19])

In [38]:
s=np.random.randint(10,20,100)
s

array([12, 15, 17, 12, 10, 17, 17, 17, 13, 11, 14, 11, 11, 13, 13, 10, 10,
       13, 18, 14, 10, 16, 12, 18, 11, 15, 14, 18, 17, 12, 17, 12, 19, 18,
       10, 12, 11, 17, 11, 18, 14, 16, 19, 10, 15, 13, 13, 16, 13, 13, 15,
       13, 13, 11, 15, 16, 12, 16, 14, 19, 10, 12, 16, 10, 12, 16, 11, 12,
       19, 14, 18, 19, 12, 15, 19, 13, 11, 14, 14, 18, 18, 13, 18, 13, 15,
       11, 14, 13, 11, 17, 14, 17, 14, 13, 11, 19, 18, 19, 13, 14])

In [39]:
f.sum()

1488

In [40]:
s.sum()

1422

In [41]:
x=((f.sum()-s.sum())/f.sum())*100  #lift
x

4.435483870967742

In [42]:
#### Basket Values= Sales/Transactions\
#### Basket Size= Units/Transactions

In [43]:
s=np.random.randint(100,600,100)
u=np.random.randint(10,60,100)
t=np.random.randint(10,20,100)

In [49]:
bv=s/t
bv

array([27.21428571, 22.91666667, 38.28571429, 18.9       ,  7.42105263,
       15.1       , 33.08333333, 13.63157895, 27.75      , 27.08333333,
       16.26315789, 22.33333333, 58.9       , 20.1875    , 59.7       ,
       36.125     , 15.15384615, 35.69230769, 18.33333333, 34.14285714,
       24.73333333, 33.4375    , 16.3125    , 29.26315789, 48.91666667,
       10.64285714, 22.29411765, 32.83333333, 48.5       , 14.41666667,
        9.0625    ,  7.38888889, 16.5       , 18.78947368, 16.17647059,
       54.8       , 20.5       , 30.47058824, 24.45454545, 38.42857143,
       12.25      , 50.27272727, 12.36842105, 27.33333333, 27.6       ,
       25.        , 29.18181818, 29.82352941, 12.68421053, 14.52631579,
       31.8       ,  8.75      , 51.27272727, 33.        , 21.6875    ,
       10.73333333,  6.89473684,  8.46666667, 21.        , 31.        ,
       35.54545455, 25.86666667, 12.70588235,  7.76470588, 13.4       ,
       44.83333333, 32.92307692, 26.7       , 52.90909091, 28.11

In [50]:
bs=u/t
bs

array([4.07142857, 0.83333333, 1.28571429, 2.9       , 0.63157895,
       1.1       , 4.75      , 2.36842105, 1.8125    , 4.16666667,
       2.47368421, 2.73333333, 4.1       , 2.125     , 3.7       ,
       1.5       , 4.46153846, 1.38461538, 1.58333333, 2.21428571,
       0.66666667, 3.375     , 1.4375    , 1.84210526, 2.41666667,
       1.14285714, 3.17647059, 2.16666667, 2.16666667, 3.83333333,
       1.8125    , 1.72222222, 4.08333333, 1.89473684, 3.23529412,
       2.3       , 3.21428571, 0.88235294, 4.54545455, 2.42857143,
       1.33333333, 4.09090909, 2.89473684, 2.61111111, 2.66666667,
       2.88235294, 4.63636364, 2.58823529, 2.31578947, 1.26315789,
       4.6       , 0.6875    , 2.09090909, 2.15384615, 1.8125    ,
       2.06666667, 2.21052632, 1.46666667, 1.0625    , 0.72222222,
       5.09090909, 2.46666667, 1.70588235, 3.29411765, 2.3       ,
       1.83333333, 3.23076923, 3.6       , 1.72727273, 1.29411765,
       2.41666667, 2.9       , 2.1875    , 0.78947368, 1.5    

In [51]:
print(bv.argmin())
print(bs.argmax())
print(bv.min())
print(bs.max())

56
60
6.894736842105263
5.090909090909091


In [52]:
bv[56]

6.894736842105263

Set 4 Functions

In [53]:
p=np.array([[1,2,3],[4,5,6],[7,8,9]])
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
p.mean()

5.0

In [55]:
p.mean(axis=0) #row

array([4., 5., 6.])

In [57]:
p.mean(axis=1) #column

array([2., 5., 8.])

Set 6

In [77]:
p=np.random.randint(1,10,100)
p

array([9, 1, 2, 9, 5, 1, 1, 3, 9, 3, 1, 7, 9, 8, 7, 9, 9, 5, 8, 3, 7, 6,
       3, 2, 1, 2, 2, 7, 8, 8, 2, 1, 3, 1, 2, 4, 9, 9, 3, 2, 8, 4, 4, 6,
       4, 4, 6, 3, 8, 4, 9, 2, 7, 9, 6, 4, 6, 9, 9, 1, 3, 3, 5, 9, 2, 7,
       8, 6, 7, 8, 1, 4, 1, 2, 6, 5, 3, 2, 7, 5, 7, 6, 5, 1, 8, 4, 7, 2,
       3, 2, 3, 9, 6, 3, 4, 6, 5, 7, 4, 7])

In [78]:
p.shape

(100,)

In [79]:
x=p.reshape(10,10)
x

array([[9, 1, 2, 9, 5, 1, 1, 3, 9, 3],
       [1, 7, 9, 8, 7, 9, 9, 5, 8, 3],
       [7, 6, 3, 2, 1, 2, 2, 7, 8, 8],
       [2, 1, 3, 1, 2, 4, 9, 9, 3, 2],
       [8, 4, 4, 6, 4, 4, 6, 3, 8, 4],
       [9, 2, 7, 9, 6, 4, 6, 9, 9, 1],
       [3, 3, 5, 9, 2, 7, 8, 6, 7, 8],
       [1, 4, 1, 2, 6, 5, 3, 2, 7, 5],
       [7, 6, 5, 1, 8, 4, 7, 2, 3, 2],
       [3, 9, 6, 3, 4, 6, 5, 7, 4, 7]])

In [80]:
x.shape

(10, 10)

In [81]:
p.reshape(25,4)

array([[9, 1, 2, 9],
       [5, 1, 1, 3],
       [9, 3, 1, 7],
       [9, 8, 7, 9],
       [9, 5, 8, 3],
       [7, 6, 3, 2],
       [1, 2, 2, 7],
       [8, 8, 2, 1],
       [3, 1, 2, 4],
       [9, 9, 3, 2],
       [8, 4, 4, 6],
       [4, 4, 6, 3],
       [8, 4, 9, 2],
       [7, 9, 6, 4],
       [6, 9, 9, 1],
       [3, 3, 5, 9],
       [2, 7, 8, 6],
       [7, 8, 1, 4],
       [1, 2, 6, 5],
       [3, 2, 7, 5],
       [7, 6, 5, 1],
       [8, 4, 7, 2],
       [3, 2, 3, 9],
       [6, 3, 4, 6],
       [5, 7, 4, 7]])

In [82]:
##### Examples

In [83]:
p=np.random.randint(10,100,(10,5))
p

array([[48, 29, 79, 50, 42],
       [53, 46, 66, 82, 54],
       [93, 61, 75, 97, 38],
       [50, 91, 28, 36, 99],
       [40, 13, 96, 54, 24],
       [37, 22, 39, 95, 42],
       [40, 39, 20, 89, 68],
       [12, 97, 45, 44, 41],
       [66, 86, 11, 62, 30],
       [37, 33, 80, 43, 69]])

In [84]:
p[0]

array([48, 29, 79, 50, 42])

In [85]:
abs(p[0]-p).sum(axis=1)

array([  0,  79, 132, 186,  63, 103, 142, 145, 167,  50])

In [86]:
abs(p[0]-p).sum(axis=1)[1:].argmin()

8

In [88]:
p=np.random.randint(1,20,(1000,3))
p

array([[19, 11,  6],
       [ 4, 18, 13],
       [ 5,  7, 16],
       ...,
       [17, 12, 11],
       [11, 16, 14],
       [ 1, 10, 13]])

In [89]:
p.shape

(1000, 3)

In [90]:
abs(p[10]-p).sum(axis=1)

array([ 8, 23, 26, 19, 18, 14, 13, 14,  5, 13,  0, 18, 23, 16, 17, 17, 15,
       18,  5, 25,  5, 29,  7, 12, 20, 14, 15, 27, 10, 27, 25, 13, 12, 12,
       25, 27, 20, 13, 20, 27, 13, 28, 17, 19, 13, 21, 15, 17, 19, 30, 12,
       25, 16, 19,  9, 16, 23, 12, 12, 10,  6, 26, 29, 13, 18, 28, 25, 18,
       31, 14,  7, 14, 14, 12, 18,  8, 20, 22, 12, 12, 13, 18, 31, 24, 27,
       11,  7, 21, 18, 15, 17, 16,  9, 21, 17, 15,  9, 23, 23,  7, 12, 22,
       18, 13,  8, 20, 23,  9, 11, 25, 12, 24, 20, 23, 16, 14, 26, 20, 12,
       25, 10, 18, 15, 13, 10, 20, 27, 17, 10,  7, 18, 38, 16,  9, 10,  8,
       21, 12,  8,  4,  8, 12,  4, 16, 25,  7, 21, 24, 20,  6, 35, 19,  9,
        9, 21, 20, 21, 23, 21, 11,  9, 25, 24, 28, 16, 25, 18, 22, 18, 15,
       12, 21, 25, 15, 16, 19, 28, 13, 17, 15, 11, 18, 16, 20, 10, 10, 19,
        8, 17,  8, 29, 33, 17, 15,  7, 15, 13, 21,  7, 12, 12, 15, 15, 14,
       12, 17, 16, 17, 24, 15, 18, 12, 26, 22, 21, 34, 26, 18, 30, 25, 22,
       13, 22, 22, 18, 21

In [91]:
p.shape[0]

1000

In [92]:
p.shape[1]

3

Experiment : An activity designed towards capturing the data 
Population : All the observations that are captured as a part of this experiement 
Sample : Subset of population and behaves like populations 
Bias : An aritificial constrain we are introducing while sampling 
Descirbes Data ( Descriptive Staistics)
    1. Mean
        1.a A.M 
        1.b G.M
        1.c H.M
    2. Mode ()
    3. Median
    4. Std Deviation 
    5. Variance 

In [97]:
p=np.random.randint(10,100,5)
p

array([90, 61, 43, 63, 75])

In [98]:
sum(p)

332

In [99]:
len(p)

5

In [100]:
mean=sum(p)/len(p)
mean

66.4

In [101]:
median=np.median(p)
median

63.0

In [102]:
abs((p-mean).sum())

2.842170943040401e-14

In [103]:
abs((p-median).sum())

17.0

Set 7

In [104]:
p=np.random.randint(10,100,20)
p

array([70, 15, 19, 61, 58, 12, 31, 48, 75, 77, 61, 26, 61, 87, 85, 46, 56,
       85, 67, 53])

In [105]:
p>50

array([ True, False, False,  True,  True, False, False, False,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True,  True])

In [106]:
p[p>50]


array([70, 61, 58, 75, 77, 61, 61, 87, 85, 56, 85, 67, 53])

In [107]:
p[p<50]

array([15, 19, 12, 31, 48, 26, 46])

K Means

In [108]:
p=np.random.randint(10,100,(1000,5))

In [109]:
p[363],p[786]

(array([11, 74, 39, 48, 12]), array([91, 47, 15, 62, 77]))

In [110]:
c1=p[363]

In [111]:
c2=p[786]

In [112]:
d1=abs(c1-p).sum(axis=1)

In [113]:
d2=abs(c2-p).sum(axis=1)

In [114]:
p[d1<d2].shape

(439, 5)

In [115]:
p[d1>d2].shape

(550, 5)

Set 8

In [116]:
p=np.random.randint(0,10,100)

In [117]:
p.mean()

4.41

In [118]:
p.std()

2.9701683453972767

In [119]:
p.var()

8.821899999999998