We have customers and the things they bought consider values , code to know which customer is closer to each other to form clusters of same kind, we should know the distance of each customer with each other to calculate this.

In [8]:
import numpy as np
x=np.random.randint(10,100,(10,5))
print(x)

[[94 71 88 22 39]
 [99 16 35 57 17]
 [12 77 99 94 80]
 [76 80 82 48 66]
 [18 25 82 60 92]
 [65 84 90 74 93]
 [64 71 30 41 49]
 [46 50 57 41 91]
 [99 98 71 52 74]
 [28 58 31 62 15]]


In [9]:
y=(x[0]-x)
y

array([[  0,   0,   0,   0,   0],
       [ -5,  55,  53, -35,  22],
       [ 82,  -6, -11, -72, -41],
       [ 18,  -9,   6, -26, -27],
       [ 76,  46,   6, -38, -53],
       [ 29, -13,  -2, -52, -54],
       [ 30,   0,  58, -19, -10],
       [ 48,  21,  31, -19, -52],
       [ -5, -27,  17, -30, -35],
       [ 66,  13,  57, -40,  24]])

In [10]:
d=y*y 
d

array([[   0,    0,    0,    0,    0],
       [  25, 3025, 2809, 1225,  484],
       [6724,   36,  121, 5184, 1681],
       [ 324,   81,   36,  676,  729],
       [5776, 2116,   36, 1444, 2809],
       [ 841,  169,    4, 2704, 2916],
       [ 900,    0, 3364,  361,  100],
       [2304,  441,  961,  361, 2704],
       [  25,  729,  289,  900, 1225],
       [4356,  169, 3249, 1600,  576]])

np.sqrt(d.sum(axis=1)[1:]).argmin() ---- Right way to find the closely related member

In [11]:
d.sum(axis=1) #cloumn wise sum

array([    0,  7568, 13746,  1846, 12181,  6634,  4725,  6771,  3168,
        9950])

In [12]:
z=d.sum(axis=1)[1:]
z

array([ 7568, 13746,  1846, 12181,  6634,  4725,  6771,  3168,  9950])

In [13]:
z.argmin()

2

In [15]:
z[2] #this value of this customer is closer to the customer 1(index0) in our data

1846

Practice: #third customer is closer to which customer?

In [29]:
a=np.random.randint(10,20,(7,4))
a

array([[10, 10, 13, 11],
       [16, 16, 10, 14],
       [10, 12, 10, 17],
       [15, 10, 12, 15],
       [17, 19, 15, 11],
       [15, 18, 17, 14],
       [17, 12, 11, 16]])

In [30]:
b=a[2]-a
b 

array([[ 0,  2, -3,  6],
       [-6, -4,  0,  3],
       [ 0,  0,  0,  0],
       [-5,  2, -2,  2],
       [-7, -7, -5,  6],
       [-5, -6, -7,  3],
       [-7,  0, -1,  1]])

In [31]:
d=b*b
d

array([[ 0,  4,  9, 36],
       [36, 16,  0,  9],
       [ 0,  0,  0,  0],
       [25,  4,  4,  4],
       [49, 49, 25, 36],
       [25, 36, 49,  9],
       [49,  0,  1,  1]])

In [34]:
z=d.sum(axis=1)[1:]
z

array([ 61,   0,  37, 159, 119,  51])

In [33]:
z.argmin()

1

In [35]:
z[1] #first customer is closely related to the third customer

0

Choose to random values from matrix to form two clusters

In [36]:
x=np.random.randint(0,10,(10,5))
x

array([[9, 7, 3, 1, 1],
       [9, 1, 6, 8, 3],
       [6, 4, 4, 3, 8],
       [1, 1, 7, 7, 6],
       [5, 1, 0, 4, 8],
       [8, 1, 9, 4, 2],
       [7, 2, 8, 6, 4],
       [5, 9, 7, 8, 6],
       [8, 8, 8, 7, 8],
       [7, 8, 3, 0, 2]])

In [37]:
r1=x[2]
r2=x[4]
print(r1)
print(r2)

[6 4 4 3 8]
[5 1 0 4 8]


In [38]:
d1=np.sqrt(((r1-x)*(r1-x)).sum(axis=1))
print(d1)
d2=np.sqrt(((r2-x)*(r2-x)).sum(axis=1))
print(d2)

[8.48528137 8.48528137 0.         7.93725393 5.19615242 8.66025404
 6.78232998 8.         7.21110255 7.93725393]
[10.90871211  9.64365076  5.19615242  8.83176087  0.         11.22497216
  9.43398113 11.53256259 11.44552314 10.67707825]


In [39]:
d1<d2

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [40]:
d2

array([10.90871211,  9.64365076,  5.19615242,  8.83176087,  0.        ,
       11.22497216,  9.43398113, 11.53256259, 11.44552314, 10.67707825])

Quantiles problem, dividing into quaters, to know the outliers from a given set of data

In [41]:
x=np.random.randint(10,100,(10,3))
x

array([[54, 21, 47],
       [63, 73, 94],
       [60, 75, 34],
       [79, 24, 44],
       [49, 13, 25],
       [55, 47, 29],
       [72, 24, 46],
       [45, 54, 82],
       [76, 69, 83],
       [69, 14, 52]])

In [42]:
c1=x[:,0]
c2=x[:,1]
c3=x[:,2]
print(c1)
print(c2)
print(c3)

[54 63 60 79 49 55 72 45 76 69]
[21 73 75 24 13 47 24 54 69 14]
[47 94 34 44 25 29 46 82 83 52]


In [43]:
q1_c1=np.quantile(c1,0.25)
q3_c1=np.quantile(c1,0.75)
iqr_c1=q3_c1-q1_c1
utv_c1=q3_c1+1.5*(q3_c1)
ltv_c1=q1_c1-1.5*(q1_c1)
print(q1_c1)
print(q3_c1)
print(iqr_c1)
print(utv_c1)
print(ltv_c1)

54.25
71.25
17.0
178.125
-27.125


In [44]:
c1>utv_c1

array([False, False, False, False, False, False, False, False, False,
       False])

In [45]:
c1<ltv_c1

array([False, False, False, False, False, False, False, False, False,
       False])

In [46]:
q1_c2=np.quantile(c2,0.25)
q3_c2=np.quantile(c2,0.75)
iqr_c2=q3_c2-q1_c2
utv_c2=q3_c1+1.5*(q3_c2)
ltv_c2=q1_c1-1.5*(q1_c2)
print(q1_c2)
print(q3_c2)
print(iqr_c2)
print(utv_c2)
print(ltv_c2)

21.75
65.25
43.5
169.125
21.625


In [47]:
c2>utv_c2

array([False, False, False, False, False, False, False, False, False,
       False])

In [48]:
c2<ltv_c2

array([ True, False, False, False,  True, False, False, False, False,
        True])

Coefficient--Correlation

In [49]:
x=np.random.randint(0,10,(10,2))
x

array([[9, 9],
       [3, 5],
       [9, 9],
       [8, 6],
       [0, 1],
       [2, 4],
       [0, 6],
       [4, 6],
       [8, 6],
       [7, 9]])

In [50]:
c1=x[:,0]
c2=x[:,1]

print(c1)
print(c2)

[9 3 9 8 0 2 0 4 8 7]
[9 5 9 6 1 4 6 6 6 9]


In [51]:
top=((c1-c1.mean())*(c2-c2.mean())).sum()
top

63.0

In [52]:
bot=np.sqrt((((c1-c1.mean())**2).sum())*(((c2-c2.mean())**2).sum()))
bot

81.94022211344073

In [53]:
top/bot

0.7688531758283585

In [54]:
np.corrcoef(c1,c2)

array([[1.        , 0.76885318],
       [0.76885318, 1.        ]])

Basic Mathematics( Descriptive Statistics)

In [57]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [58]:
x.mean()

2.5

In [59]:
x.std()

1.118033988749895

In [60]:
x.var()

1.25

In [61]:
x=np.random.randint(0,10,(5,2))

In [62]:
c1=x[:,0]
c2=x[:,1]

In [63]:
np.corrcoef(x[:,0],x[:,1])

array([[1.        , 0.35993702],
       [0.35993702, 1.        ]])