In [1]:
a=[1,2,3]

In [2]:
a/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [3]:
import numpy as np
x=np.array(a)

In [4]:
x/2

array([0.5, 1. , 1.5])

In [5]:
x

array([1, 2, 3])

In [6]:
### Interview Question

In [7]:
a=[1,2,3,4]
b=[1,'analytics','data']

In [8]:
x=np.array(a)
y=np.array(b)

In [10]:
print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
type(a[0]),type(a[1]),type(a[2]),type(a[3])

(int, int, int, int)

In [12]:
type(x[0]),type(x[1]),type(x[2]),type(x[3])

(numpy.int32, numpy.int32, numpy.int32, numpy.int32)

In [13]:
type(b[0]),type(b[1]),type(b[2])

(int, str, str)

In [14]:
type(y[0]),type(y[1]),type(y[2])

(numpy.str_, numpy.str_, numpy.str_)

In [15]:
#### Functions

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
### Set 2 : Random Functions

In [29]:
np.random.randint(0,10)

2

In [30]:
np.random.randint(0,10,5)

array([6, 0, 4, 4, 5])

In [31]:
np.random.randint(0,10,(5,2))

array([[1, 2],
       [5, 5],
       [5, 7],
       [3, 8],
       [3, 5]])

In [33]:
np.random.randn(10)

array([ 0.08465423,  2.54430566,  0.58121972, -0.82697373, -0.45628079,
       -2.19177683,  0.63145861, -1.22433145,  0.93224209,  1.04509445])

In [39]:
np.random.rand(10)

array([0.92160306, 0.26347982, 0.24560959, 0.66822551, 0.57492058,
       0.98899237, 0.16585236, 0.95309675, 0.31183437, 0.74238696])

In [40]:
### Set 3

In [47]:
x=np.random.randint(0,10,5)

In [48]:
x

array([2, 2, 9, 3, 0])

In [49]:
x.min()

0

In [50]:
x.max()

9

In [51]:
x.argmax()

2

In [52]:
x.argmin()

4

In [ ]:
#### Basket Values= Sales/Transactions\
#### Basket Size= Units/Transactions

In [54]:
s=np.random.randint(100,600,100)
u=np.random.randint(10,60,100)
t=np.random.randint(10,20,100)

In [55]:
bv=s/t
bs=u/t

In [64]:
print(bv.argmin())
print(bs.argmax())
print(bv.min())
print(bs.max())

73
70
5.888888888888889
5.5


In [61]:
bv[73]

5.888888888888889

In [65]:
#### Set 4 Functions

In [68]:
p=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [67]:
np.array([[1,2,3],[4,6],[7,8,9]])

array([list([1, 2, 3]), list([4, 6]), list([7, 8, 9])], dtype=object)

In [69]:
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
p.sum()

45

In [71]:
p.sum(axis=1)

array([ 6, 15, 24])

In [72]:
p.sum(axis=0)

array([12, 15, 18])

In [73]:
p.mean()

5.0

In [74]:
p.mean(axis=1)

array([2., 5., 8.])

In [75]:
##### Examples

In [82]:
p=np.random.randint(10,100,(10,5))

In [83]:
p

array([[39, 56, 64, 50, 10],
       [60, 57, 22, 75, 35],
       [66, 65, 94, 25, 23],
       [68, 37, 15, 54, 52],
       [13, 83, 80, 82, 54],
       [69, 66, 80, 62, 13],
       [63, 34, 12, 15, 93],
       [45, 57, 29, 83, 34],
       [14, 62, 79, 19, 36],
       [27, 29, 49, 95, 17]])

In [80]:
p[0]

array([8, 4, 8, 4, 2])

In [86]:
abs(p[0]-p).sum(axis=1)

array([  0, 114, 104, 143, 145,  71, 216,  99, 103, 106])

In [89]:
abs(p[0]-p).sum(axis=1)[1:].argmin()

4

In [90]:
####

In [95]:
p=np.random.randint(1,20,(1000,3))

In [97]:
p.shape

(1000, 3)

In [102]:
abs(p[10]-p).sum(axis=1)

array([14, 19, 16, 28, 16, 29, 20, 11, 18, 31,  0,  4, 23, 12,  7, 12, 31,
       13, 14, 21, 26, 11, 24, 23, 17, 20, 12, 20, 16,  4, 23, 19,  5, 14,
        5, 22, 20, 19, 17, 26, 12, 36, 24, 20, 31, 12, 30, 24,  9, 15, 19,
       16,  9, 15, 10, 15, 29,  6, 22, 21, 19, 11, 11, 27, 12,  9, 19, 13,
       19,  9, 10, 14,  2, 17, 25, 17, 18, 26, 29, 17, 31, 15, 17, 27, 12,
       15, 35, 19, 22, 16, 21, 23, 15,  9, 21, 24, 25, 18, 25, 12, 17, 24,
       10, 23, 17, 22, 21, 23, 21,  4, 18, 20, 27, 14, 24, 16, 20, 22, 25,
       27, 26, 14, 24, 21, 11, 18, 15, 19, 21, 28, 24, 18,  7, 13, 23, 20,
        6, 27, 34, 25,  3, 27, 10, 17, 25,  8, 15, 15, 26, 25,  5, 18, 25,
       32, 29, 22,  6, 23, 25, 15,  9, 15, 26, 29, 13,  8, 17, 16, 26, 15,
       19, 14, 27, 16, 14, 25, 22, 15, 12, 21, 34, 29, 20, 16, 22, 26, 18,
       12, 28, 29, 18, 25, 27, 27, 20, 13, 15, 16, 30, 33, 21, 18, 21, 19,
       10, 23, 18, 16, 19, 16, 12, 17, 28, 15, 23, 19,  7, 16, 24, 29, 28,
       28, 17, 25, 17, 14

In [106]:
p.shape[0]

1000

In [107]:
p.shape[1]

3

In [ ]:
##### Set 6

In [108]:
p=np.random.randint(0,10,30)

In [109]:
p

array([9, 7, 1, 0, 9, 7, 3, 0, 5, 6, 6, 5, 9, 0, 5, 4, 4, 2, 4, 9, 2, 4,
       1, 8, 0, 8, 1, 7, 3, 3])

In [110]:
p.shape

(30,)

In [112]:
p.reshape(10,3)

array([[9, 7, 1],
       [0, 9, 7],
       [3, 0, 5],
       [6, 6, 5],
       [9, 0, 5],
       [4, 4, 2],
       [4, 9, 2],
       [4, 1, 8],
       [0, 8, 1],
       [7, 3, 3]])

In [113]:
p.reshape(15,2)

array([[9, 7],
       [1, 0],
       [9, 7],
       [3, 0],
       [5, 6],
       [6, 5],
       [9, 0],
       [5, 4],
       [4, 2],
       [4, 9],
       [2, 4],
       [1, 8],
       [0, 8],
       [1, 7],
       [3, 3]])

In [114]:
p.reshape(6,5)

array([[9, 7, 1, 0, 9],
       [7, 3, 0, 5, 6],
       [6, 5, 9, 0, 5],
       [4, 4, 2, 4, 9],
       [2, 4, 1, 8, 0],
       [8, 1, 7, 3, 3]])

In [115]:
p.reshape(5,6)

array([[9, 7, 1, 0, 9, 7],
       [3, 0, 5, 6, 6, 5],
       [9, 0, 5, 4, 4, 2],
       [4, 9, 2, 4, 1, 8],
       [0, 8, 1, 7, 3, 3]])

In [116]:
#### Set 7

In [117]:
p=np.random.randint(10,100,20)

In [122]:
p

array([74, 89, 13, 80, 80, 60, 30, 47, 16, 91, 77, 82, 89, 43, 55, 47, 61,
       31, 10, 87])

In [123]:
p>50

array([ True,  True, False,  True,  True,  True, False, False, False,
        True,  True,  True,  True, False,  True, False,  True, False,
       False,  True])

In [120]:
p[p>50]

array([74, 89, 80, 80, 60, 91, 77, 82, 89, 55, 61, 87])

In [121]:
p[p<50]

array([13, 30, 47, 16, 43, 47, 31, 10])

#### K Means

In [127]:
p=np.random.randint(10,100,(1000,5))

In [129]:
p[363],p[786]

(array([47, 23, 81, 37, 62]), array([95, 83, 54, 52, 75]))

In [131]:
c1=p[363]

In [130]:
c2=p[786]

In [137]:
d1=abs(c1-p).sum(axis=1)

In [138]:
d2=abs(c2-p).sum(axis=1)

In [143]:
p[d1<d2].shape

(596, 5)

In [144]:
p[d1>d2].shape

(404, 5)

In [145]:
#### Set 8

In [146]:
p=np.random.randint(0,10,100)

In [148]:
p.mean()

4.45

In [149]:
p.std()

2.8155816450602176

In [150]:
p.var()

7.9275

<img src="Image.png" alt="Smiley face" height="1000" width="1000">


###### Experiment : An activity designed towards capturing the data <br>
###### Population : All the observations that are captured as a part of this experiement  <br>
###### Sample : Subset of population and behaves like populations <br>
###### Bias :  An aritificial constrain we are introducing while sampling  <br>
###### Descirbes Data ( Descriptive Staistics)
        1. Mean
            1.a A.M 
            1.b G.M
            1.c H.M
        2. Mode ()
        3. Median
        4. Std Deviation 
        5. Variance 
        

In [156]:
p=np.random.randint(10,100,5)

In [168]:
p

array([55, 69, 30, 76, 70])